### ISSUE TITLE
don't do initial commands in pyats connect

### ISSUE THREAD

**Issue by mgdransfield** [CiscoDevNet/virl2-client#12]
Issue when using cml client to access an sd-wan device via pyats. The initial commands fail as they are not allowed on sd-wan device. The testbed is generated on the fly so I can't see a way to set init_exec_commands=[], init_config_commands=[] on the connect line in virl2_client/models/cl_pyats.py  run_command.

**Comment by xorrkaz** [comment]
Seems like being able to pass `init_exec_commands` and `init_config_commands` to the `run_command()` and `run_config_command()` methods might do the trick (where those are passed to `dev.connect()`).  Maybe something like:

```python
def run_command(self, node_label, command, init_exec_commands=None, init_config_commands=None):
...
    extra_params = {}
    if init_exec_commands:
        extra_params["init_exec_commands"] = init_exec_commands
    if init_config_commands:
        extra_params["init_config_commands"] = init_config_commands

    pyats_device.connect(log_stdout=False, **extra_params)
```

**Comment by mgdransfield** [comment]
def run_command(self, node_label, command, init_exec_commands=[], init_config_commands=[]):
...

    pyats_device.connect(log_stdout=False, init_exec_commands=init_exec_commands,init_config_commands=init_config_commands)

works although changes default behaviour

**Comment by xorrkaz** [comment]
Yes, this does change the default behavior, which is why I suggested my approach above.  This way, clients can pass different initial commands to the two cl_pyats methods without changing the default.

**Comment by rschmied** [comment]
can we close this?
