### ISSUE TITLE
Node.stop() and node.wipe() don't wait properly

### ISSUE THREAD

**Issue by xorrkaz** [CiscoDevNet/virl2-client#2]
If you call node.stop() or node.wipe() with the wait=True flag, they still return immediately.  I think this is because both methods use the same `has_converged()` code that node.start() uses.  This might be fine, but my guess is the `/check_if_converged` API endpoint is not doing the right thing for the stop and wipe operations.

For wipe, this may not be a big deal.  For stop, my code assumes that when stop(wait=True) completes, the node is down and can be wiped.  This is not deterministically true, and therefore I had to add:

```python
node.stop(wait=True)
while node.is_active():
    time.sleep(1)
```

I'd like the wait=True to be honored.

**Comment by rschmied** [comment]
We can look into this. need to create a JIRA for this, please. Thanks.

**Comment by xorrkaz** [comment]
Done.  I've created an internal ticket.

**Comment by rschmied** [comment]
i've verified that this is not an issue anymore with 2.1 code.
