### ISSUE TITLE
CML Image Not Ready

### ISSUE THREAD

**Issue by Bienveniedos** [CiscoDevNet/virl2-client#88]
I have installed CML and can get everything to work except for the images included with the environment. I have tried re-download the refplat and attaching the new one in case something got corrupted along the way, but that didn't work. I am at a loss currently, this is the first time I have worked with CML but I am a networking professional in a cisco environment. Any help would be awesome, the screen shot below depicts the issue. Cheers!

![Screenshot 2024-03-04 215929](https://github.com/CiscoDevNet/virl2-client/assets/162275095/94221c43-e117-45d3-baff-eced555a1744)

**Comment by virlos** [comment]
Hi, this repository is meant to be used for use and development of automation around CML. It is not a place to ask for support-related questions relating to general CML installation and troubleshooting. 

A better place would be to try the Cisco Learning Network. You might want to read on the following post; it contains a documentation link for copying reference platforms to disk manually.
https://learningnetwork.cisco.com/s/question/0D56e0000DZ2DrPCQV/issue-with-copy-refplat-iso-on-261

**Comment by Bienveniedos** [comment]
Thank you! Sorry about that.
